import type { GraphEdgeSpec, GraphNodeSpec, GraphPhaseSpec, GraphSpec } from '../types';

export const GRAPH_PHASES: GraphPhaseSpec[] = [
  {
    id: 'prepare',
    label: 'Prepare',
    rows: [0, 1],
    blurb: 'Read sources, plan the piece, write the first draft, generate figures, then art-direction review and redraw.',
  },
  {
    id: 'review',
    label: 'Review loop',
    rows: [2, 3],
    blurb: 'Specialist reviewers plus house-skill lint, supervisor, substance plus voice rewrite, then an editor score gate.',
  },
  {
    id: 'finish',
    label: 'Finish',
    rows: [4],
    blurb: 'Headline, style polish, grounding check, your approval, then export.',
  },
];

export const GRAPH_NODES: GraphNodeSpec[] = [
  {
    id: 'ingest',
    label: 'Ingest',
    row: 0,
    col: 0,
    phase: 'prepare',
    does: 'Parse uploads into blocks and load the Medium style guide.',
    visit_means: 'Times source files were parsed. This node runs once at the start.',
  },
  {
    id: 'plan',
    label: 'Plan',
    row: 0,
    col: 1,
    phase: 'prepare',
    does: 'Write the title, thesis, pyramid outline, and image prompts.',
    visit_means: 'Times an outline was written. Usually once.',
  },
  {
    id: 'web_research',
    label: 'Research',
    row: 0,
    col: 2,
    phase: 'prepare',
    does: 'Optional web snippets. Uploads stay the primary source.',
    visit_means: 'Times web research ran. Once if you enabled it, otherwise a quiet pass.',
  },
  {
    id: 'draft',
    label: 'Draft',
    row: 0,
    col: 3,
    phase: 'prepare',
    does: 'Write the first full Markdown article from the plan and sources.',
    visit_means: 'Times the first draft was written. Later edits happen in Rewrite, not here.',
  },
  {
    id: 'image_gen',
    label: 'Images',
    row: 0,
    col: 4,
    phase: 'prepare',
    does: 'Generate 2–5 illustrations and inject them into the draft.',
    visit_means: 'Times images were generated. Art-direction happens next, not inside this node.',
  },
  {
    id: 'image_review',
    label: 'Art review',
    row: 1,
    col: 4,
    phase: 'prepare',
    does: 'Vision-check each figure. Reject blobs, stock laptops, and illegible mush.',
    visit_means: 'Times art-direction ran. Goes up again after every redraw.',
  },
  {
    id: 'image_redraw',
    label: 'Redraw',
    row: 1,
    col: 5,
    phase: 'prepare',
    does: 'Regenerate only the figures that failed art-direction, then send them back to review.',
    visit_means: 'Times rejected figures were regenerated. Capped at two redraws.',
  },
  {
    id: 'reviewer_technical',
    label: 'Technical',
    row: 2,
    col: 0,
    phase: 'review',
    does: 'Check technical accuracy, then re-check the same findings after each rewrite.',
    visit_means: 'Review passes this specialist ran. It goes up by 1 after the first draft and after every rewrite.',
  },
  {
    id: 'reviewer_style',
    label: 'Style',
    row: 2,
    col: 1,
    phase: 'review',
    does: 'Check Medium voice, pacing, and house-style rules.',
    visit_means: 'Review passes this specialist ran. One pass per loop.',
  },
  {
    id: 'reviewer_structure',
    label: 'Structure',
    row: 2,
    col: 2,
    phase: 'review',
    does: 'Check flow, headings, and whether the pyramid outline still holds.',
    visit_means: 'Review passes this specialist ran. One pass per loop.',
  },
  {
    id: 'reviewer_grounding',
    label: 'Grounding',
    row: 2,
    col: 3,
    phase: 'review',
    does: 'Check claims against the uploaded source material.',
    visit_means: 'Review passes this specialist ran. One pass per loop.',
  },
  {
    id: 'reviewer_reader',
    label: 'Reader',
    row: 2,
    col: 4,
    phase: 'review',
    does: 'Read as a Medium subscriber: hook, definition before jargon, skimable H2s, usable takeaway.',
    visit_means: 'Review passes this specialist ran. One pass per loop.',
  },
  {
    id: 'reviewer_skills',
    label: 'House skill',
    row: 2,
    col: 5,
    phase: 'review',
    does: 'Deterministic lint of backend/skills/medium.md: banned phrases, disclosure, word count, H2s, golden sentences.',
    visit_means: 'Times the house-skill lint ran. One pass per loop. This is not an LLM guess.',
  },
  {
    id: 'supervisor',
    label: 'Supervisor',
    row: 3,
    col: 1,
    phase: 'review',
    does: 'Merge findings and keep unresolved IDs open. Any leftover finding sends the draft back.',
    visit_means:
      'Times the exit gate scored the draft. Usually one more than Rewrite, because the first review happens before any rewrite.',
  },
  {
    id: 'rewrite',
    label: 'Rewrite',
    row: 3,
    col: 2,
    phase: 'review',
    does: 'Substance rewrite so every still-open finding is actually addressed.',
    visit_means: 'Review iterations performed. This is how many times the agent tried to close the previous findings.',
  },
  {
    id: 'rewrite_voice',
    label: 'Voice',
    row: 3,
    col: 3,
    phase: 'review',
    does: 'Second rewrite agent. Polishes Medium voice without dropping facts or shrinking the piece.',
    visit_means: 'Times the voice pass ran. Fires after every substance rewrite.',
  },
  {
    id: 'editor_score',
    label: 'Editor',
    row: 3,
    col: 5,
    phase: 'review',
    does: 'Score the article 1–10. Below the publication bar, inject defects and rewrite again.',
    visit_means: 'Times the editor-in-chief scored the draft.',
  },
  {
    id: 'headline',
    label: 'Headline',
    row: 4,
    col: 0,
    phase: 'finish',
    does: 'Rewrite the title, subtitle, and dek so a skimmer stops.',
    visit_means: 'Times the headline pass ran. Usually once, after the editor ships.',
  },
  {
    id: 'style_pass',
    label: 'Style pass',
    row: 4,
    col: 1,
    phase: 'finish',
    does: 'Terminal polish for Medium voice. Strips leftover draft artifacts.',
    visit_means: 'Times the finishing style pass ran. Fires after the headline.',
  },
  {
    id: 'final_rewrite',
    label: 'Final',
    row: 4,
    col: 2,
    phase: 'finish',
    does: 'Last structural cleanup before the grounding recheck.',
    visit_means: 'Times the final cleanup ran. Can run again if grounding still sees drift.',
  },
  {
    id: 'grounding_recheck',
    label: 'Ground check',
    row: 4,
    col: 3,
    phase: 'finish',
    does: 'Confirm the finished draft still matches the source material.',
    visit_means: 'Times the finished draft was checked against sources.',
  },
  {
    id: 'human_gate',
    label: 'Human gate',
    row: 4,
    col: 4,
    phase: 'finish',
    does: 'Pause for you to approve or send the draft back with notes.',
    visit_means: 'Times the pipeline paused for a human decision.',
  },
  {
    id: 'export',
    label: 'Export',
    row: 4,
    col: 5,
    phase: 'finish',
    does: 'Build clipboard Markdown and HTML for pasting into Medium.',
    visit_means: 'Times an export package was built. Fires after you approve.',
  },
];

export const GRAPH_EDGES: GraphEdgeSpec[] = [
  { from: 'ingest', to: 'plan', kind: 'always', label: 'sources ready', when: 'Always, after files are parsed.' },
  { from: 'plan', to: 'web_research', kind: 'always', label: 'outline ready', when: 'Always. Research may be a quiet pass.' },
  { from: 'web_research', to: 'draft', kind: 'always', label: 'write draft', when: 'Always. The first article is written here.' },
  { from: 'draft', to: 'image_gen', kind: 'always', label: 'illustrate', when: 'Always. Images come from the plan prompts.' },
  { from: 'image_gen', to: 'image_review', kind: 'always', label: 'art direction', when: 'Always. Every generated figure is vision-checked.' },
  { from: 'image_review', to: 'image_redraw', kind: 'loop', label: 'rejected', when: 'If a figure fails art-direction and redraws remain under the cap of two.' },
  { from: 'image_redraw', to: 'image_review', kind: 'loop', label: 're-check', when: 'After every redraw. Only the new bytes are judged.' },
  { from: 'image_review', to: 'reviewer_technical', kind: 'fanout', label: 'fan out', when: 'After figures pass or the redraw cap is hit. All five reviewers run together.' },
  { from: 'image_review', to: 'reviewer_style', kind: 'fanout', label: 'fan out', when: 'After figures pass or the redraw cap is hit. All five reviewers run together.' },
  { from: 'image_review', to: 'reviewer_structure', kind: 'fanout', label: 'fan out', when: 'After figures pass or the redraw cap is hit. All five reviewers run together.' },
  { from: 'image_review', to: 'reviewer_grounding', kind: 'fanout', label: 'fan out', when: 'After figures pass or the redraw cap is hit. All five reviewers run together.' },
  { from: 'image_review', to: 'reviewer_reader', kind: 'fanout', label: 'fan out', when: 'After figures pass or the redraw cap is hit. All six reviewers run together.' },
  { from: 'image_review', to: 'reviewer_skills', kind: 'fanout', label: 'fan out', when: 'After figures pass or the redraw cap is hit. House-skill lint runs with the specialists.' },
  { from: 'reviewer_technical', to: 'supervisor', kind: 'always', label: 'findings', when: 'Always. Each reviewer sends its verdict to the supervisor.' },
  { from: 'reviewer_style', to: 'supervisor', kind: 'always', label: 'findings', when: 'Always. Each reviewer sends its verdict to the supervisor.' },
  { from: 'reviewer_structure', to: 'supervisor', kind: 'always', label: 'findings', when: 'Always. Each reviewer sends its verdict to the supervisor.' },
  { from: 'reviewer_grounding', to: 'supervisor', kind: 'always', label: 'findings', when: 'Always. Each reviewer sends its verdict to the supervisor.' },
  { from: 'reviewer_reader', to: 'supervisor', kind: 'always', label: 'findings', when: 'Always. Each reviewer sends its verdict to the supervisor.' },
  { from: 'reviewer_skills', to: 'supervisor', kind: 'always', label: 'findings', when: 'Always. Failed house-skill checks become findings with stable IDs.' },
  { from: 'supervisor', to: 'rewrite', kind: 'loop', label: 'findings remain', when: 'If any finding is still open and the cap has not been hit.' },
  { from: 'rewrite', to: 'rewrite_voice', kind: 'always', label: 'polish voice', when: 'Always after a substance rewrite.' },
  { from: 'rewrite_voice', to: 'reviewer_technical', kind: 'loop', label: 're-review', when: 'After voice polish, specialists verdict the same finding IDs.' },
  { from: 'rewrite_voice', to: 'reviewer_style', kind: 'loop', label: 're-review', when: 'After voice polish, specialists verdict the same finding IDs.' },
  { from: 'rewrite_voice', to: 'reviewer_structure', kind: 'loop', label: 're-review', when: 'After voice polish, specialists verdict the same finding IDs.' },
  { from: 'rewrite_voice', to: 'reviewer_grounding', kind: 'loop', label: 're-review', when: 'After voice polish, specialists verdict the same finding IDs.' },
  { from: 'rewrite_voice', to: 'reviewer_reader', kind: 'loop', label: 're-review', when: 'After voice polish, specialists verdict the same finding IDs.' },
  { from: 'rewrite_voice', to: 'reviewer_skills', kind: 'loop', label: 're-lint', when: 'After voice polish, house-skill lint re-checks the same IDs.' },
  { from: 'rewrite_voice', to: 'editor_score', kind: 'loop', label: 'editor recheck', when: 'If the editor injected defects, skip the specialists and score again.' },
  { from: 'supervisor', to: 'editor_score', kind: 'exit', label: 'clean or cap', when: 'If there are no open findings, or the loop stalled, or the max review iterations were reached.' },
  { from: 'editor_score', to: 'rewrite', kind: 'loop', label: 'below bar', when: 'If the editor score is under 8 and editor retries remain.' },
  { from: 'editor_score', to: 'headline', kind: 'exit', label: 'publication bar', when: 'If the score is at least 8, or the editor retry cap was hit.' },
  { from: 'headline', to: 'style_pass', kind: 'always', label: 'polish', when: 'Always after the editor ships.' },
  { from: 'style_pass', to: 'final_rewrite', kind: 'always', label: 'cleanup', when: 'Always after the finishing style pass.' },
  { from: 'final_rewrite', to: 'grounding_recheck', kind: 'always', label: 'verify sources', when: 'Always. The finished draft is checked against uploads.' },
  { from: 'grounding_recheck', to: 'human_gate', kind: 'exit', label: 'grounded', when: 'If the draft matches the sources, or drift retries are exhausted.' },
  { from: 'grounding_recheck', to: 'final_rewrite', kind: 'loop', label: 'still drifting', when: 'If grounding finds drift and it has retried fewer than twice.' },
  { from: 'human_gate', to: 'export', kind: 'exit', label: 'approved', when: 'If you approve the article.' },
  { from: 'human_gate', to: 'rewrite', kind: 'hitl', label: 'changes requested', when: 'If you send the draft back with notes.' },
];

const NODE_BY_ID = Object.fromEntries(GRAPH_NODES.map((node) => [node.id, node]));

export function mergeGraph(graph?: GraphSpec): { nodes: GraphNodeSpec[]; edges: GraphEdgeSpec[]; phases: GraphPhaseSpec[] } {
  const incoming = graph?.nodes?.length ? graph.nodes : GRAPH_NODES;
  const nodes = incoming.map((node) => ({ ...NODE_BY_ID[node.id], ...node }));
  const edges = (graph?.edges?.length ? graph.edges : GRAPH_EDGES).map((edge) => {
    const fallback = GRAPH_EDGES.find((item) => item.from === edge.from && item.to === edge.to);
    return { ...fallback, ...edge };
  });
  return {
    nodes,
    edges,
    phases: graph?.phases?.length ? graph.phases : GRAPH_PHASES,
  };
}

export function nodeLabel(id: string): string {
  return NODE_BY_ID[id]?.label || id.replace(/_/g, ' ');
}
